# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 594)
        MainWindow.setStyleSheet("QTableView { gridline-color: gray }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.mapFrame = QtWidgets.QFrame(self.splitter)
        self.mapFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mapFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mapFrame.setObjectName("mapFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mapFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mapCanvas = MyQt4MplCanvas(self.mapFrame)
        self.mapCanvas.setObjectName("mapCanvas")
        self.verticalLayout_4.addWidget(self.mapCanvas)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mapZoomInButton = QtWidgets.QToolButton(self.mapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapZoomInButton.sizePolicy().hasHeightForWidth())
        self.mapZoomInButton.setSizePolicy(sizePolicy)
        self.mapZoomInButton.setObjectName("mapZoomInButton")
        self.horizontalLayout_3.addWidget(self.mapZoomInButton)
        self.mapZoomOutButton = QtWidgets.QToolButton(self.mapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapZoomOutButton.sizePolicy().hasHeightForWidth())
        self.mapZoomOutButton.setSizePolicy(sizePolicy)
        self.mapZoomOutButton.setObjectName("mapZoomOutButton")
        self.horizontalLayout_3.addWidget(self.mapZoomOutButton)
        self.mapResetButton = QtWidgets.QToolButton(self.mapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapResetButton.sizePolicy().hasHeightForWidth())
        self.mapResetButton.setSizePolicy(sizePolicy)
        self.mapResetButton.setObjectName("mapResetButton")
        self.horizontalLayout_3.addWidget(self.mapResetButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.eventAndStationWidget = QtWidgets.QWidget(self.splitter)
        self.eventAndStationWidget.setObjectName("eventAndStationWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.eventAndStationWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.eventAndStationWidget)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.eventsWidget = QtWidgets.QWidget(self.splitter_2)
        self.eventsWidget.setObjectName("eventsWidget")
        self.eventsLayout = QtWidgets.QVBoxLayout(self.eventsWidget)
        self.eventsLayout.setContentsMargins(0, 0, 0, 0)
        self.eventsLayout.setSpacing(0)
        self.eventsLayout.setObjectName("eventsLayout")
        self.eventsButtonLayout = QtWidgets.QHBoxLayout()
        self.eventsButtonLayout.setSpacing(12)
        self.eventsButtonLayout.setObjectName("eventsButtonLayout")
        self.toggleEventOptions = QtWidgets.QToolButton(self.eventsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleEventOptions.sizePolicy().hasHeightForWidth())
        self.toggleEventOptions.setSizePolicy(sizePolicy)
        self.toggleEventOptions.setCheckable(True)
        self.toggleEventOptions.setChecked(True)
        self.toggleEventOptions.setObjectName("toggleEventOptions")
        self.eventsButtonLayout.addWidget(self.toggleEventOptions)
        self.getEventsButton = QtWidgets.QPushButton(self.eventsWidget)
        self.getEventsButton.setDefault(False)
        self.getEventsButton.setObjectName("getEventsButton")
        self.eventsButtonLayout.addWidget(self.getEventsButton)
        self.eventsButtonLayout.setStretch(1, 1)
        self.eventsLayout.addLayout(self.eventsButtonLayout)
        self.eventsTable = QtWidgets.QTableWidget(self.eventsWidget)
        self.eventsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.eventsTable.setAlternatingRowColors(True)
        self.eventsTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.eventsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.eventsTable.setShowGrid(False)
        self.eventsTable.setWordWrap(False)
        self.eventsTable.setObjectName("eventsTable")
        self.eventsTable.setColumnCount(0)
        self.eventsTable.setRowCount(0)
        self.eventsTable.verticalHeader().setVisible(False)
        self.eventsLayout.addWidget(self.eventsTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eventSelectionLabel = QtWidgets.QLabel(self.eventsWidget)
        self.eventSelectionLabel.setText("")
        self.eventSelectionLabel.setObjectName("eventSelectionLabel")
        self.horizontalLayout.addWidget(self.eventSelectionLabel)
        self.allEventSelectionButton = QtWidgets.QToolButton(self.eventsWidget)
        self.allEventSelectionButton.setObjectName("allEventSelectionButton")
        self.horizontalLayout.addWidget(self.allEventSelectionButton)
        self.clearEventSelectionButton = QtWidgets.QToolButton(self.eventsWidget)
        self.clearEventSelectionButton.setObjectName("clearEventSelectionButton")
        self.horizontalLayout.addWidget(self.clearEventSelectionButton)
        self.eventsLayout.addLayout(self.horizontalLayout)
        self.stationsWidget = QtWidgets.QWidget(self.splitter_2)
        self.stationsWidget.setObjectName("stationsWidget")
        self.stationsLayout = QtWidgets.QVBoxLayout(self.stationsWidget)
        self.stationsLayout.setContentsMargins(0, 0, 0, 0)
        self.stationsLayout.setSpacing(0)
        self.stationsLayout.setObjectName("stationsLayout")
        self.stationsButtonLayout = QtWidgets.QHBoxLayout()
        self.stationsButtonLayout.setSpacing(12)
        self.stationsButtonLayout.setObjectName("stationsButtonLayout")
        self.getStationsButton = QtWidgets.QPushButton(self.stationsWidget)
        self.getStationsButton.setDefault(False)
        self.getStationsButton.setObjectName("getStationsButton")
        self.stationsButtonLayout.addWidget(self.getStationsButton)
        self.toggleStationOptions = QtWidgets.QToolButton(self.stationsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleStationOptions.sizePolicy().hasHeightForWidth())
        self.toggleStationOptions.setSizePolicy(sizePolicy)
        self.toggleStationOptions.setCheckable(True)
        self.toggleStationOptions.setChecked(True)
        self.toggleStationOptions.setObjectName("toggleStationOptions")
        self.stationsButtonLayout.addWidget(self.toggleStationOptions)
        self.stationsButtonLayout.setStretch(0, 1)
        self.stationsLayout.addLayout(self.stationsButtonLayout)
        self.stationsTable = QtWidgets.QTableWidget(self.stationsWidget)
        self.stationsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stationsTable.setAlternatingRowColors(True)
        self.stationsTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.stationsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.stationsTable.setShowGrid(False)
        self.stationsTable.setWordWrap(False)
        self.stationsTable.setObjectName("stationsTable")
        self.stationsTable.setColumnCount(0)
        self.stationsTable.setRowCount(0)
        self.stationsTable.verticalHeader().setVisible(False)
        self.stationsLayout.addWidget(self.stationsTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stationSelectionLabel = QtWidgets.QLabel(self.stationsWidget)
        self.stationSelectionLabel.setText("")
        self.stationSelectionLabel.setObjectName("stationSelectionLabel")
        self.horizontalLayout_2.addWidget(self.stationSelectionLabel)
        self.allStationSelectionButton = QtWidgets.QToolButton(self.stationsWidget)
        self.allStationSelectionButton.setObjectName("allStationSelectionButton")
        self.horizontalLayout_2.addWidget(self.allStationSelectionButton)
        self.clearStationSelectionButton = QtWidgets.QToolButton(self.stationsWidget)
        self.clearStationSelectionButton.setObjectName("clearStationSelectionButton")
        self.horizontalLayout_2.addWidget(self.clearStationSelectionButton)
        self.stationsLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.waveformButtonLayout = QtWidgets.QHBoxLayout()
        self.waveformButtonLayout.setObjectName("waveformButtonLayout")
        self.getWaveformsButton = QtWidgets.QPushButton(self.eventAndStationWidget)
        self.getWaveformsButton.setDefault(True)
        self.getWaveformsButton.setObjectName("getWaveformsButton")
        self.waveformButtonLayout.addWidget(self.getWaveformsButton)
        self.verticalLayout_3.addLayout(self.waveformButtonLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.eventOptionsDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.eventOptionsDockWidget.setFloating(False)
        self.eventOptionsDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.eventOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.eventOptionsDockWidget.setObjectName("eventOptionsDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.eventOptionsDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.eventOptionsDockWidget)
        self.stationOptionsDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.stationOptionsDockWidget.setFloating(False)
        self.stationOptionsDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.stationOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.stationOptionsDockWidget.setObjectName("stationOptionsDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.stationOptionsDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.stationOptionsDockWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.getEventsButton, self.getStationsButton)
        MainWindow.setTabOrder(self.getStationsButton, self.eventsTable)
        MainWindow.setTabOrder(self.eventsTable, self.stationsTable)
        MainWindow.setTabOrder(self.stationsTable, self.getWaveformsButton)
        MainWindow.setTabOrder(self.getWaveformsButton, self.clearEventSelectionButton)
        MainWindow.setTabOrder(self.clearEventSelectionButton, self.clearStationSelectionButton)
        MainWindow.setTabOrder(self.clearStationSelectionButton, self.toggleEventOptions)
        MainWindow.setTabOrder(self.toggleEventOptions, self.toggleStationOptions)
        MainWindow.setTabOrder(self.toggleStationOptions, self.mapZoomInButton)
        MainWindow.setTabOrder(self.mapZoomInButton, self.mapZoomOutButton)
        MainWindow.setTabOrder(self.mapZoomOutButton, self.mapResetButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mapZoomInButton.setText(_translate("MainWindow", "Zoom In"))
        self.mapZoomOutButton.setText(_translate("MainWindow", "Zoom Out"))
        self.mapResetButton.setText(_translate("MainWindow", "Reset"))
        self.toggleEventOptions.setText(_translate("MainWindow", "< Options"))
        self.getEventsButton.setText(_translate("MainWindow", "Get Events"))
        self.eventsTable.setSortingEnabled(True)
        self.allEventSelectionButton.setText(_translate("MainWindow", "Select All"))
        self.clearEventSelectionButton.setText(_translate("MainWindow", "Clear Selection"))
        self.getStationsButton.setText(_translate("MainWindow", "Get Stations"))
        self.toggleStationOptions.setText(_translate("MainWindow", "Options >"))
        self.stationsTable.setSortingEnabled(True)
        self.allStationSelectionButton.setText(_translate("MainWindow", "Select All"))
        self.clearStationSelectionButton.setText(_translate("MainWindow", "Clear Selection"))
        self.getWaveformsButton.setText(_translate("MainWindow", "Get Waveforms"))
        self.eventOptionsDockWidget.setWindowTitle(_translate("MainWindow", "Event Options"))
        self.stationOptionsDockWidget.setWindowTitle(_translate("MainWindow", "Station Options"))

from pyweed.gui.uic.MyQt4MplCanvas import MyQt4MplCanvas
