# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/uic/MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1030, 487)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.mapFrame = QtGui.QFrame(self.splitter)
        self.mapFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mapFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mapFrame.setObjectName(_fromUtf8("mapFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mapFrame)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.map_canvas = MyQt4MplCanvas(self.mapFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_canvas.sizePolicy().hasHeightForWidth())
        self.map_canvas.setSizePolicy(sizePolicy)
        self.map_canvas.setObjectName(_fromUtf8("map_canvas"))
        self.verticalLayout_2.addWidget(self.map_canvas)
        self.eventAndStationWidget = QtGui.QWidget(self.splitter)
        self.eventAndStationWidget.setObjectName(_fromUtf8("eventAndStationWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.eventAndStationWidget)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.eventAndStationLayout = QtGui.QHBoxLayout()
        self.eventAndStationLayout.setObjectName(_fromUtf8("eventAndStationLayout"))
        self.eventsLayout = QtGui.QVBoxLayout()
        self.eventsLayout.setSpacing(0)
        self.eventsLayout.setObjectName(_fromUtf8("eventsLayout"))
        self.eventsButtonLayout = QtGui.QHBoxLayout()
        self.eventsButtonLayout.setSpacing(12)
        self.eventsButtonLayout.setObjectName(_fromUtf8("eventsButtonLayout"))
        self.getEventsButton = QtGui.QPushButton(self.eventAndStationWidget)
        self.getEventsButton.setObjectName(_fromUtf8("getEventsButton"))
        self.eventsButtonLayout.addWidget(self.getEventsButton)
        self.toggleEventOptions = QtGui.QPushButton(self.eventAndStationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleEventOptions.sizePolicy().hasHeightForWidth())
        self.toggleEventOptions.setSizePolicy(sizePolicy)
        self.toggleEventOptions.setCheckable(True)
        self.toggleEventOptions.setChecked(True)
        self.toggleEventOptions.setObjectName(_fromUtf8("toggleEventOptions"))
        self.eventsButtonLayout.addWidget(self.toggleEventOptions)
        self.eventsLayout.addLayout(self.eventsButtonLayout)
        self.eventsTable = QtGui.QTableWidget(self.eventAndStationWidget)
        self.eventsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.eventsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.eventsTable.setObjectName(_fromUtf8("eventsTable"))
        self.eventsTable.setColumnCount(0)
        self.eventsTable.setRowCount(0)
        self.eventsLayout.addWidget(self.eventsTable)
        self.eventAndStationLayout.addLayout(self.eventsLayout)
        self.stationsLayout = QtGui.QVBoxLayout()
        self.stationsLayout.setSpacing(0)
        self.stationsLayout.setObjectName(_fromUtf8("stationsLayout"))
        self.stationsButtonLayout = QtGui.QHBoxLayout()
        self.stationsButtonLayout.setSpacing(12)
        self.stationsButtonLayout.setObjectName(_fromUtf8("stationsButtonLayout"))
        self.getStationsButton = QtGui.QPushButton(self.eventAndStationWidget)
        self.getStationsButton.setObjectName(_fromUtf8("getStationsButton"))
        self.stationsButtonLayout.addWidget(self.getStationsButton)
        self.toggleStationOptions = QtGui.QPushButton(self.eventAndStationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleStationOptions.sizePolicy().hasHeightForWidth())
        self.toggleStationOptions.setSizePolicy(sizePolicy)
        self.toggleStationOptions.setCheckable(True)
        self.toggleStationOptions.setChecked(True)
        self.toggleStationOptions.setObjectName(_fromUtf8("toggleStationOptions"))
        self.stationsButtonLayout.addWidget(self.toggleStationOptions)
        self.stationsLayout.addLayout(self.stationsButtonLayout)
        self.stationsTable = QtGui.QTableWidget(self.eventAndStationWidget)
        self.stationsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.stationsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.stationsTable.setObjectName(_fromUtf8("stationsTable"))
        self.stationsTable.setColumnCount(0)
        self.stationsTable.setRowCount(0)
        self.stationsLayout.addWidget(self.stationsTable)
        self.eventAndStationLayout.addLayout(self.stationsLayout)
        self.verticalLayout_4.addLayout(self.eventAndStationLayout)
        self.waveformButtonLayout = QtGui.QHBoxLayout()
        self.waveformButtonLayout.setObjectName(_fromUtf8("waveformButtonLayout"))
        self.getWaveformsButton = QtGui.QPushButton(self.eventAndStationWidget)
        self.getWaveformsButton.setObjectName(_fromUtf8("getWaveformsButton"))
        self.waveformButtonLayout.addWidget(self.getWaveformsButton)
        self.verticalLayout_4.addLayout(self.waveformButtonLayout)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.eventOptionsDockWidget = QtGui.QDockWidget(MainWindow)
        self.eventOptionsDockWidget.setFloating(False)
        self.eventOptionsDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.eventOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.eventOptionsDockWidget.setObjectName(_fromUtf8("eventOptionsDockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.eventOptionsDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.eventOptionsDockWidget)
        self.stationOptionsDockWidget = QtGui.QDockWidget(MainWindow)
        self.stationOptionsDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.stationOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.stationOptionsDockWidget.setObjectName(_fromUtf8("stationOptionsDockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.stationOptionsDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.stationOptionsDockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.getEventsButton.setText(_translate("MainWindow", "Get Events", None))
        self.toggleEventOptions.setText(_translate("MainWindow", "Options", None))
        self.eventsTable.setSortingEnabled(True)
        self.getStationsButton.setText(_translate("MainWindow", "Get Stations", None))
        self.toggleStationOptions.setText(_translate("MainWindow", "Options", None))
        self.stationsTable.setSortingEnabled(True)
        self.getWaveformsButton.setText(_translate("MainWindow", "Get Waveforms", None))
        self.eventOptionsDockWidget.setWindowTitle(_translate("MainWindow", "Event Options", None))
        self.stationOptionsDockWidget.setWindowTitle(_translate("MainWindow", "Station Options", None))

from MyQt4MplCanvas import MyQt4MplCanvas
