# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/uic/StationOptionsWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationOptionsWidget(object):
    def setupUi(self, StationOptionsWidget):
        StationOptionsWidget.setObjectName(_fromUtf8("StationOptionsWidget"))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StationOptionsWidget.sizePolicy().hasHeightForWidth())
        StationOptionsWidget.setSizePolicy(sizePolicy)
        StationOptionsWidget.setStyleSheet(_fromUtf8("QLineEdit {\n"
"    width: 5em;\n"
"}"))
        self.verticalLayout = QtGui.QVBoxLayout(StationOptionsWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.SNCLGroupBox = QtGui.QGroupBox(StationOptionsWidget)
        self.SNCLGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SNCLGroupBox.setObjectName(_fromUtf8("SNCLGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.SNCLGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setHorizontalSpacing(4)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.networkLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.networkLabel.setObjectName(_fromUtf8("networkLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.networkLabel)
        self.networkLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.networkLineEdit.setObjectName(_fromUtf8("networkLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.networkLineEdit)
        self.stationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.stationLineEdit.setObjectName(_fromUtf8("stationLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.stationLineEdit)
        self.locationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.locationLabel)
        self.locationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.locationLineEdit.setObjectName(_fromUtf8("locationLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.locationLineEdit)
        self.channelLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.channelLabel.setObjectName(_fromUtf8("channelLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.channelLabel)
        self.channelLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.channelLineEdit.setObjectName(_fromUtf8("channelLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.channelLineEdit)
        self.stationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.stationLabel.setObjectName(_fromUtf8("stationLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.stationLabel)
        self.horizontalLayout_13.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.SNCLGroupBox)
        self.timeGroupBox = QtGui.QGroupBox(StationOptionsWidget)
        self.timeGroupBox.setObjectName(_fromUtf8("timeGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.timeGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.timeBetweenRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeBetweenRadioButton.setEnabled(True)
        self.timeBetweenRadioButton.setChecked(True)
        self.timeBetweenRadioButton.setObjectName(_fromUtf8("timeBetweenRadioButton"))
        self.verticalLayout_2.addWidget(self.timeBetweenRadioButton)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(4)
        self.formLayout_2.setVerticalSpacing(1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.starttimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.starttimeLabel.setObjectName(_fromUtf8("starttimeLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.starttimeLabel)
        self.starttimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starttimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.starttimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.starttimeDateTimeEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.starttimeDateTimeEdit.setCalendarPopup(True)
        self.starttimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeDateTimeEdit.setObjectName(_fromUtf8("starttimeDateTimeEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.starttimeDateTimeEdit)
        self.endtimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.endtimeLabel.setObjectName(_fromUtf8("endtimeLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.endtimeLabel)
        self.endtimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endtimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.endtimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.endtimeDateTimeEdit.setProperty("showGroupSeparator", False)
        self.endtimeDateTimeEdit.setCalendarPopup(True)
        self.endtimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endtimeDateTimeEdit.setObjectName(_fromUtf8("endtimeDateTimeEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.endtimeDateTimeEdit)
        self.horizontalLayout_10.addLayout(self.formLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.timeDuringEventsRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeDuringEventsRadioButton.setObjectName(_fromUtf8("timeDuringEventsRadioButton"))
        self.verticalLayout_2.addWidget(self.timeDuringEventsRadioButton)
        self.verticalLayout.addWidget(self.timeGroupBox)
        self.locationGroupBox = QtGui.QGroupBox(StationOptionsWidget)
        self.locationGroupBox.setObjectName(_fromUtf8("locationGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.locationGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.locationRangeRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationRangeRadioButton.setChecked(True)
        self.locationRangeRadioButton.setObjectName(_fromUtf8("locationRangeRadioButton"))
        self.verticalLayout_4.addWidget(self.locationRangeRadioButton)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.locationRangeNorthInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeNorthInput.setMinimum(-90.0)
        self.locationRangeNorthInput.setMaximum(90.0)
        self.locationRangeNorthInput.setObjectName(_fromUtf8("locationRangeNorthInput"))
        self.horizontalLayout_4.addWidget(self.locationRangeNorthInput)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.locationRangeWestInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeWestInput.setMinimum(-180.0)
        self.locationRangeWestInput.setMaximum(180.0)
        self.locationRangeWestInput.setObjectName(_fromUtf8("locationRangeWestInput"))
        self.horizontalLayout.addWidget(self.locationRangeWestInput)
        self.locationRangeEastInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeEastInput.setMinimum(-180.0)
        self.locationRangeEastInput.setMaximum(180.0)
        self.locationRangeEastInput.setObjectName(_fromUtf8("locationRangeEastInput"))
        self.horizontalLayout.addWidget(self.locationRangeEastInput)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.locationRangeSouthInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeSouthInput.setMinimum(-90.0)
        self.locationRangeSouthInput.setMaximum(90.0)
        self.locationRangeSouthInput.setObjectName(_fromUtf8("locationRangeSouthInput"))
        self.horizontalLayout_5.addWidget(self.locationRangeSouthInput)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.locationDistanceFromPointRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromPointRadioButton.setEnabled(True)
        self.locationDistanceFromPointRadioButton.setObjectName(_fromUtf8("locationDistanceFromPointRadioButton"))
        self.verticalLayout_4.addWidget(self.locationDistanceFromPointRadioButton)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(24, -1, -1, -1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_14.setSpacing(4)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.distanceFromPointMinRadiusInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointMinRadiusInput.setMinimum(0.0)
        self.distanceFromPointMinRadiusInput.setMaximum(180.0)
        self.distanceFromPointMinRadiusInput.setObjectName(_fromUtf8("distanceFromPointMinRadiusInput"))
        self.horizontalLayout_14.addWidget(self.distanceFromPointMinRadiusInput)
        self.label_2 = QtGui.QLabel(self.locationGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_14.addWidget(self.label_2)
        self.distanceFromPointMaxRadiusInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointMaxRadiusInput.setMinimum(0.0)
        self.distanceFromPointMaxRadiusInput.setMaximum(180.0)
        self.distanceFromPointMaxRadiusInput.setObjectName(_fromUtf8("distanceFromPointMaxRadiusInput"))
        self.horizontalLayout_14.addWidget(self.distanceFromPointMaxRadiusInput)
        self.label_8 = QtGui.QLabel(self.locationGroupBox)
        self.label_8.setEnabled(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_6 = QtGui.QLabel(self.locationGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_15.addWidget(self.label_6)
        self.distanceFromPointEastInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointEastInput.setMinimum(-180.0)
        self.distanceFromPointEastInput.setMaximum(180.0)
        self.distanceFromPointEastInput.setObjectName(_fromUtf8("distanceFromPointEastInput"))
        self.horizontalLayout_15.addWidget(self.distanceFromPointEastInput)
        self.label_14 = QtGui.QLabel(self.locationGroupBox)
        self.label_14.setEnabled(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.distanceFromPointNorthInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointNorthInput.setMinimum(-90.0)
        self.distanceFromPointNorthInput.setMaximum(90.0)
        self.distanceFromPointNorthInput.setObjectName(_fromUtf8("distanceFromPointNorthInput"))
        self.horizontalLayout_15.addWidget(self.distanceFromPointNorthInput)
        self.label_7 = QtGui.QLabel(self.locationGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.locationDistanceFromEventsRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromEventsRadioButton.setEnabled(False)
        self.locationDistanceFromEventsRadioButton.setObjectName(_fromUtf8("locationDistanceFromEventsRadioButton"))
        self.verticalLayout_4.addWidget(self.locationDistanceFromEventsRadioButton)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_4.setContentsMargins(24, -1, -1, -1)
        self.formLayout_4.setHorizontalSpacing(4)
        self.formLayout_4.setVerticalSpacing(1)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_9 = QtGui.QLabel(self.locationGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.distanceFromEventsMinRadiusInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromEventsMinRadiusInput.setMinimum(0.0)
        self.distanceFromEventsMinRadiusInput.setMaximum(180.0)
        self.distanceFromEventsMinRadiusInput.setObjectName(_fromUtf8("distanceFromEventsMinRadiusInput"))
        self.horizontalLayout_11.addWidget(self.distanceFromEventsMinRadiusInput)
        self.label_3 = QtGui.QLabel(self.locationGroupBox)
        self.label_3.setEnabled(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_12 = QtGui.QLabel(self.locationGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.distanceFromEventsMaxRadiusInput = QtGui.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromEventsMaxRadiusInput.setMinimum(0.0)
        self.distanceFromEventsMaxRadiusInput.setMaximum(180.0)
        self.distanceFromEventsMaxRadiusInput.setObjectName(_fromUtf8("distanceFromEventsMaxRadiusInput"))
        self.horizontalLayout_12.addWidget(self.distanceFromEventsMaxRadiusInput)
        self.label_5 = QtGui.QLabel(self.locationGroupBox)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.locationGroupBox)

        self.retranslateUi(StationOptionsWidget)
        QtCore.QMetaObject.connectSlotsByName(StationOptionsWidget)
        StationOptionsWidget.setTabOrder(self.networkLineEdit, self.stationLineEdit)
        StationOptionsWidget.setTabOrder(self.stationLineEdit, self.locationLineEdit)
        StationOptionsWidget.setTabOrder(self.locationLineEdit, self.channelLineEdit)
        StationOptionsWidget.setTabOrder(self.channelLineEdit, self.timeBetweenRadioButton)
        StationOptionsWidget.setTabOrder(self.timeBetweenRadioButton, self.starttimeDateTimeEdit)
        StationOptionsWidget.setTabOrder(self.starttimeDateTimeEdit, self.endtimeDateTimeEdit)
        StationOptionsWidget.setTabOrder(self.endtimeDateTimeEdit, self.timeDuringEventsRadioButton)
        StationOptionsWidget.setTabOrder(self.timeDuringEventsRadioButton, self.locationRangeRadioButton)
        StationOptionsWidget.setTabOrder(self.locationRangeRadioButton, self.locationDistanceFromPointRadioButton)
        StationOptionsWidget.setTabOrder(self.locationDistanceFromPointRadioButton, self.locationDistanceFromEventsRadioButton)

    def retranslateUi(self, StationOptionsWidget):
        self.SNCLGroupBox.setTitle(_translate("StationOptionsWidget", "SNCL", None))
        self.networkLabel.setText(_translate("StationOptionsWidget", "Networks", None))
        self.networkLineEdit.setText(_translate("StationOptionsWidget", "_GSN", None))
        self.stationLineEdit.setText(_translate("StationOptionsWidget", "*", None))
        self.locationLabel.setText(_translate("StationOptionsWidget", "Locations", None))
        self.locationLineEdit.setText(_translate("StationOptionsWidget", "*", None))
        self.channelLabel.setText(_translate("StationOptionsWidget", "Channels", None))
        self.channelLineEdit.setText(_translate("StationOptionsWidget", "?HZ", None))
        self.stationLabel.setText(_translate("StationOptionsWidget", "Stations", None))
        self.timeGroupBox.setTitle(_translate("StationOptionsWidget", "Time", None))
        self.timeBetweenRadioButton.setText(_translate("StationOptionsWidget", "Between start and end times", None))
        self.starttimeLabel.setText(_translate("StationOptionsWidget", "Start", None))
        self.starttimeDateTimeEdit.setDisplayFormat(_translate("StationOptionsWidget", "yyyy-MM-dd hh:mm:ss", None))
        self.endtimeLabel.setText(_translate("StationOptionsWidget", "End", None))
        self.endtimeDateTimeEdit.setDisplayFormat(_translate("StationOptionsWidget", "yyyy-MM-dd hh:mm:ss", None))
        self.timeDuringEventsRadioButton.setText(_translate("StationOptionsWidget", "Operational during selected events", None))
        self.locationGroupBox.setTitle(_translate("StationOptionsWidget", "Location", None))
        self.locationRangeRadioButton.setText(_translate("StationOptionsWidget", "Within lat/lon box", None))
        self.locationDistanceFromPointRadioButton.setText(_translate("StationOptionsWidget", "Distance from point", None))
        self.label_2.setText(_translate("StationOptionsWidget", "-", None))
        self.label_8.setText(_translate("StationOptionsWidget", "degrees", None))
        self.label_6.setText(_translate("StationOptionsWidget", "from", None))
        self.label_14.setText(_translate("StationOptionsWidget", "E", None))
        self.label_7.setText(_translate("StationOptionsWidget", "N", None))
        self.locationDistanceFromEventsRadioButton.setText(_translate("StationOptionsWidget", "Distance from selected events", None))
        self.label_9.setText(_translate("StationOptionsWidget", "between", None))
        self.label_3.setText(_translate("StationOptionsWidget", "degrees", None))
        self.label_12.setText(_translate("StationOptionsWidget", "and", None))
        self.label_5.setText(_translate("StationOptionsWidget", "degrees", None))

