# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StationOptionsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StationOptionsWidget(object):
    def setupUi(self, StationOptionsWidget):
        StationOptionsWidget.setObjectName("StationOptionsWidget")
        StationOptionsWidget.resize(265, 671)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StationOptionsWidget.sizePolicy().hasHeightForWidth())
        StationOptionsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(StationOptionsWidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeGroupBox = QtWidgets.QGroupBox(StationOptionsWidget)
        self.timeGroupBox.setObjectName("timeGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.timeGroupBox)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setHorizontalSpacing(4)
        self.formLayout_2.setVerticalSpacing(1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.starttimeLabel = QtWidgets.QLabel(self.timeGroupBox)
        self.starttimeLabel.setObjectName("starttimeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.starttimeLabel)
        self.starttimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starttimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.starttimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.starttimeDateTimeEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.starttimeDateTimeEdit.setCalendarPopup(True)
        self.starttimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeDateTimeEdit.setObjectName("starttimeDateTimeEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.starttimeDateTimeEdit)
        self.endtimeLabel = QtWidgets.QLabel(self.timeGroupBox)
        self.endtimeLabel.setObjectName("endtimeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.endtimeLabel)
        self.endtimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endtimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.endtimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.endtimeDateTimeEdit.setProperty("showGroupSeparator", False)
        self.endtimeDateTimeEdit.setCalendarPopup(True)
        self.endtimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endtimeDateTimeEdit.setObjectName("endtimeDateTimeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endtimeDateTimeEdit)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.time30DaysToolButton = QtWidgets.QToolButton(self.timeGroupBox)
        self.time30DaysToolButton.setObjectName("time30DaysToolButton")
        self.horizontalLayout_7.addWidget(self.time30DaysToolButton)
        self.time1YearToolButton = QtWidgets.QToolButton(self.timeGroupBox)
        self.time1YearToolButton.setObjectName("time1YearToolButton")
        self.horizontalLayout_7.addWidget(self.time1YearToolButton)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.timeGroupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.timeFromEventsToolButton = QtWidgets.QToolButton(self.timeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeFromEventsToolButton.sizePolicy().hasHeightForWidth())
        self.timeFromEventsToolButton.setSizePolicy(sizePolicy)
        self.timeFromEventsToolButton.setObjectName("timeFromEventsToolButton")
        self.verticalLayout_2.addWidget(self.timeFromEventsToolButton)
        self.verticalLayout.addWidget(self.timeGroupBox)
        self.SNCLGroupBox = QtWidgets.QGroupBox(StationOptionsWidget)
        self.SNCLGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SNCLGroupBox.setObjectName("SNCLGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SNCLGroupBox)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setHorizontalSpacing(4)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.networkLabel = QtWidgets.QLabel(self.SNCLGroupBox)
        self.networkLabel.setObjectName("networkLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.networkLabel)
        self.networkLineEdit = QtWidgets.QLineEdit(self.SNCLGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.networkLineEdit.sizePolicy().hasHeightForWidth())
        self.networkLineEdit.setSizePolicy(sizePolicy)
        self.networkLineEdit.setObjectName("networkLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.networkLineEdit)
        self.stationLineEdit = QtWidgets.QLineEdit(self.SNCLGroupBox)
        self.stationLineEdit.setObjectName("stationLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stationLineEdit)
        self.locationLabel = QtWidgets.QLabel(self.SNCLGroupBox)
        self.locationLabel.setObjectName("locationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.locationLabel)
        self.locationLineEdit = QtWidgets.QLineEdit(self.SNCLGroupBox)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.locationLineEdit)
        self.channelLabel = QtWidgets.QLabel(self.SNCLGroupBox)
        self.channelLabel.setObjectName("channelLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.channelLabel)
        self.channelLineEdit = QtWidgets.QLineEdit(self.SNCLGroupBox)
        self.channelLineEdit.setObjectName("channelLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.channelLineEdit)
        self.stationLabel = QtWidgets.QLabel(self.SNCLGroupBox)
        self.stationLabel.setObjectName("stationLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stationLabel)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.SNCLGroupBox)
        self.locationGroupBox = QtWidgets.QGroupBox(StationOptionsWidget)
        self.locationGroupBox.setObjectName("locationGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.locationGroupBox)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.locationGlobalRadioButton = QtWidgets.QRadioButton(self.locationGroupBox)
        self.locationGlobalRadioButton.setChecked(False)
        self.locationGlobalRadioButton.setObjectName("locationGlobalRadioButton")
        self.horizontalLayout_3.addWidget(self.locationGlobalRadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.locationGroupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.locationRangeRadioButton = QtWidgets.QRadioButton(self.locationGroupBox)
        self.locationRangeRadioButton.setChecked(False)
        self.locationRangeRadioButton.setObjectName("locationRangeRadioButton")
        self.horizontalLayout_8.addWidget(self.locationRangeRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.locationRangeNorthDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeNorthDoubleSpinBox.setMinimum(-90.0)
        self.locationRangeNorthDoubleSpinBox.setMaximum(90.0)
        self.locationRangeNorthDoubleSpinBox.setObjectName("locationRangeNorthDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.locationRangeNorthDoubleSpinBox)
        spacerItem4 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locationRangeWestDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeWestDoubleSpinBox.setMinimum(-180.0)
        self.locationRangeWestDoubleSpinBox.setMaximum(180.0)
        self.locationRangeWestDoubleSpinBox.setObjectName("locationRangeWestDoubleSpinBox")
        self.horizontalLayout.addWidget(self.locationRangeWestDoubleSpinBox)
        self.locationRangeEastDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeEastDoubleSpinBox.setMinimum(-180.0)
        self.locationRangeEastDoubleSpinBox.setMaximum(180.0)
        self.locationRangeEastDoubleSpinBox.setObjectName("locationRangeEastDoubleSpinBox")
        self.horizontalLayout.addWidget(self.locationRangeEastDoubleSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.locationRangeSouthDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.locationRangeSouthDoubleSpinBox.setMinimum(-90.0)
        self.locationRangeSouthDoubleSpinBox.setMaximum(90.0)
        self.locationRangeSouthDoubleSpinBox.setObjectName("locationRangeSouthDoubleSpinBox")
        self.horizontalLayout_5.addWidget(self.locationRangeSouthDoubleSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.drawLocationRangeToolButton = QtWidgets.QToolButton(self.locationGroupBox)
        self.drawLocationRangeToolButton.setCheckable(True)
        self.drawLocationRangeToolButton.setObjectName("drawLocationRangeToolButton")
        self.verticalLayout_7.addWidget(self.drawLocationRangeToolButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.line_2 = QtWidgets.QFrame(self.locationGroupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.locationDistanceFromPointRadioButton = QtWidgets.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromPointRadioButton.setEnabled(True)
        self.locationDistanceFromPointRadioButton.setObjectName("locationDistanceFromPointRadioButton")
        self.horizontalLayout_9.addWidget(self.locationDistanceFromPointRadioButton)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_14.setSpacing(4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.distanceFromPointMinRadiusDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointMinRadiusDoubleSpinBox.setMinimum(0.0)
        self.distanceFromPointMinRadiusDoubleSpinBox.setMaximum(180.0)
        self.distanceFromPointMinRadiusDoubleSpinBox.setObjectName("distanceFromPointMinRadiusDoubleSpinBox")
        self.horizontalLayout_14.addWidget(self.distanceFromPointMinRadiusDoubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.distanceFromPointMaxRadiusDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointMaxRadiusDoubleSpinBox.setMinimum(0.0)
        self.distanceFromPointMaxRadiusDoubleSpinBox.setMaximum(180.0)
        self.distanceFromPointMaxRadiusDoubleSpinBox.setObjectName("distanceFromPointMaxRadiusDoubleSpinBox")
        self.horizontalLayout_14.addWidget(self.distanceFromPointMaxRadiusDoubleSpinBox)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.distanceFromPointNorthDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointNorthDoubleSpinBox.setMinimum(-90.0)
        self.distanceFromPointNorthDoubleSpinBox.setMaximum(90.0)
        self.distanceFromPointNorthDoubleSpinBox.setObjectName("distanceFromPointNorthDoubleSpinBox")
        self.horizontalLayout_15.addWidget(self.distanceFromPointNorthDoubleSpinBox)
        self.label_12 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.distanceFromPointEastDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromPointEastDoubleSpinBox.setMinimum(-180.0)
        self.distanceFromPointEastDoubleSpinBox.setMaximum(180.0)
        self.distanceFromPointEastDoubleSpinBox.setObjectName("distanceFromPointEastDoubleSpinBox")
        self.horizontalLayout_15.addWidget(self.distanceFromPointEastDoubleSpinBox)
        self.horizontalLayout_15.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.drawDistanceFromPointToolButton = QtWidgets.QToolButton(self.locationGroupBox)
        self.drawDistanceFromPointToolButton.setCheckable(True)
        self.drawDistanceFromPointToolButton.setObjectName("drawDistanceFromPointToolButton")
        self.verticalLayout_3.addWidget(self.drawDistanceFromPointToolButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        self.line = QtWidgets.QFrame(self.locationGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.locationDistanceFromEventsRadioButton = QtWidgets.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromEventsRadioButton.setEnabled(True)
        self.locationDistanceFromEventsRadioButton.setObjectName("locationDistanceFromEventsRadioButton")
        self.horizontalLayout_10.addWidget(self.locationDistanceFromEventsRadioButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setSpacing(4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.distanceFromEventsMinDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromEventsMinDoubleSpinBox.setMinimum(0.0)
        self.distanceFromEventsMinDoubleSpinBox.setMaximum(180.0)
        self.distanceFromEventsMinDoubleSpinBox.setObjectName("distanceFromEventsMinDoubleSpinBox")
        self.horizontalLayout_16.addWidget(self.distanceFromEventsMinDoubleSpinBox)
        self.label_14 = QtWidgets.QLabel(self.locationGroupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.distanceFromEventsMaxDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.locationGroupBox)
        self.distanceFromEventsMaxDoubleSpinBox.setMinimum(0.0)
        self.distanceFromEventsMaxDoubleSpinBox.setMaximum(180.0)
        self.distanceFromEventsMaxDoubleSpinBox.setObjectName("distanceFromEventsMaxDoubleSpinBox")
        self.horizontalLayout_16.addWidget(self.distanceFromEventsMaxDoubleSpinBox)
        self.horizontalLayout_16.setStretch(0, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout.addWidget(self.locationGroupBox)
        self.line_5 = QtWidgets.QFrame(StationOptionsWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.locationFromEventsToolButton = QtWidgets.QToolButton(StationOptionsWidget)
        self.locationFromEventsToolButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationFromEventsToolButton.sizePolicy().hasHeightForWidth())
        self.locationFromEventsToolButton.setSizePolicy(sizePolicy)
        self.locationFromEventsToolButton.setObjectName("locationFromEventsToolButton")
        self.verticalLayout.addWidget(self.locationFromEventsToolButton)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)

        self.retranslateUi(StationOptionsWidget)
        QtCore.QMetaObject.connectSlotsByName(StationOptionsWidget)
        StationOptionsWidget.setTabOrder(self.networkLineEdit, self.stationLineEdit)
        StationOptionsWidget.setTabOrder(self.stationLineEdit, self.locationLineEdit)
        StationOptionsWidget.setTabOrder(self.locationLineEdit, self.channelLineEdit)
        StationOptionsWidget.setTabOrder(self.channelLineEdit, self.starttimeDateTimeEdit)
        StationOptionsWidget.setTabOrder(self.starttimeDateTimeEdit, self.endtimeDateTimeEdit)

    def retranslateUi(self, StationOptionsWidget):
        _translate = QtCore.QCoreApplication.translate
        self.timeGroupBox.setTitle(_translate("StationOptionsWidget", "Time"))
        self.starttimeLabel.setText(_translate("StationOptionsWidget", "min"))
        self.starttimeDateTimeEdit.setDisplayFormat(_translate("StationOptionsWidget", "yyyy-MM-dd hh:mm:ss"))
        self.endtimeLabel.setText(_translate("StationOptionsWidget", "max"))
        self.endtimeDateTimeEdit.setDisplayFormat(_translate("StationOptionsWidget", "yyyy-MM-dd hh:mm:ss"))
        self.time30DaysToolButton.setText(_translate("StationOptionsWidget", "Last 30 days"))
        self.time1YearToolButton.setText(_translate("StationOptionsWidget", "Last year"))
        self.timeFromEventsToolButton.setText(_translate("StationOptionsWidget", ">> Copy from Event Options"))
        self.SNCLGroupBox.setTitle(_translate("StationOptionsWidget", "SNCL"))
        self.networkLabel.setText(_translate("StationOptionsWidget", "net"))
        self.networkLineEdit.setText(_translate("StationOptionsWidget", "_GSN"))
        self.stationLineEdit.setText(_translate("StationOptionsWidget", "*"))
        self.locationLabel.setText(_translate("StationOptionsWidget", "loc"))
        self.locationLineEdit.setText(_translate("StationOptionsWidget", "*"))
        self.channelLabel.setText(_translate("StationOptionsWidget", "cha"))
        self.channelLineEdit.setText(_translate("StationOptionsWidget", "?HZ"))
        self.stationLabel.setText(_translate("StationOptionsWidget", "sta"))
        self.locationGroupBox.setTitle(_translate("StationOptionsWidget", "Location"))
        self.locationGlobalRadioButton.setText(_translate("StationOptionsWidget", "Global"))
        self.locationRangeRadioButton.setText(_translate("StationOptionsWidget", "Within lat/lon box"))
        self.drawLocationRangeToolButton.setText(_translate("StationOptionsWidget", "Draw on map"))
        self.locationDistanceFromPointRadioButton.setText(_translate("StationOptionsWidget", "Distance from point"))
        self.label_2.setText(_translate("StationOptionsWidget", "min"))
        self.label_5.setText(_translate("StationOptionsWidget", "max"))
        self.label_6.setText(_translate("StationOptionsWidget", "lat"))
        self.label_12.setText(_translate("StationOptionsWidget", "lon"))
        self.drawDistanceFromPointToolButton.setText(_translate("StationOptionsWidget", "Draw on map"))
        self.locationDistanceFromEventsRadioButton.setText(_translate("StationOptionsWidget", "Distance from selected events"))
        self.label_3.setText(_translate("StationOptionsWidget", "min"))
        self.label_14.setText(_translate("StationOptionsWidget", "max"))
        self.locationFromEventsToolButton.setText(_translate("StationOptionsWidget", ">> Copy from Event Options"))

