# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaveformDialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WaveformDialog(object):
    def setupUi(self, WaveformDialog):
        WaveformDialog.setObjectName("WaveformDialog")
        WaveformDialog.resize(1284, 724)
        self.verticalLayout = QtWidgets.QVBoxLayout(WaveformDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(WaveformDialog)
        self.topFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadGroupBox = QtWidgets.QGroupBox(self.topFrame)
        self.downloadGroupBox.setEnabled(True)
        self.downloadGroupBox.setObjectName("downloadGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.downloadGroupBox)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.secondsBeforeLabel = QtWidgets.QLabel(self.downloadGroupBox)
        self.secondsBeforeLabel.setObjectName("secondsBeforeLabel")
        self.gridLayout.addWidget(self.secondsBeforeLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.downloadGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.secondsAfterPhaseComboBox = QtWidgets.QComboBox(self.downloadGroupBox)
        self.secondsAfterPhaseComboBox.setObjectName("secondsAfterPhaseComboBox")
        self.gridLayout.addWidget(self.secondsAfterPhaseComboBox, 1, 3, 1, 1)
        self.secondsBeforePhaseComboBox = QtWidgets.QComboBox(self.downloadGroupBox)
        self.secondsBeforePhaseComboBox.setObjectName("secondsBeforePhaseComboBox")
        self.gridLayout.addWidget(self.secondsBeforePhaseComboBox, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.secondsAfterSpinBox = QtWidgets.QSpinBox(self.downloadGroupBox)
        self.secondsAfterSpinBox.setMaximum(21600)
        self.secondsAfterSpinBox.setSingleStep(100)
        self.secondsAfterSpinBox.setProperty("value", 600)
        self.secondsAfterSpinBox.setObjectName("secondsAfterSpinBox")
        self.gridLayout.addWidget(self.secondsAfterSpinBox, 1, 1, 1, 1)
        self.secondsBeforeSpinBox = QtWidgets.QSpinBox(self.downloadGroupBox)
        self.secondsBeforeSpinBox.setMaximum(3600)
        self.secondsBeforeSpinBox.setSingleStep(10)
        self.secondsBeforeSpinBox.setProperty("value", 60)
        self.secondsBeforeSpinBox.setObjectName("secondsBeforeSpinBox")
        self.gridLayout.addWidget(self.secondsBeforeSpinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.downloadGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.secondsAfterLabel = QtWidgets.QLabel(self.downloadGroupBox)
        self.secondsAfterLabel.setObjectName("secondsAfterLabel")
        self.gridLayout.addWidget(self.secondsAfterLabel, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.widget_5 = QtWidgets.QWidget(self.downloadGroupBox)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.downloadPushButton = QtWidgets.QPushButton(self.widget_5)
        self.downloadPushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.downloadPushButton.setCheckable(False)
        self.downloadPushButton.setObjectName("downloadPushButton")
        self.horizontalLayout_7.addWidget(self.downloadPushButton)
        self.downloadStatusLabel = QtWidgets.QLabel(self.widget_5)
        self.downloadStatusLabel.setObjectName("downloadStatusLabel")
        self.horizontalLayout_7.addWidget(self.downloadStatusLabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.downloadGroupBox)
        self.saveGroupBox = QtWidgets.QGroupBox(self.topFrame)
        self.saveGroupBox.setEnabled(True)
        self.saveGroupBox.setObjectName("saveGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.saveGroupBox)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveFormatComboBox = QtWidgets.QComboBox(self.saveGroupBox)
        self.saveFormatComboBox.setObjectName("saveFormatComboBox")
        self.horizontalLayout_4.addWidget(self.saveFormatComboBox)
        self.sacUseEventTimeCheckBox = QtWidgets.QCheckBox(self.saveGroupBox)
        self.sacUseEventTimeCheckBox.setWhatsThis("")
        self.sacUseEventTimeCheckBox.setObjectName("sacUseEventTimeCheckBox")
        self.horizontalLayout_4.addWidget(self.sacUseEventTimeCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.saveDirectoryLabel = QtWidgets.QLabel(self.saveGroupBox)
        self.saveDirectoryLabel.setObjectName("saveDirectoryLabel")
        self.gridLayout_2.addWidget(self.saveDirectoryLabel, 0, 0, 1, 1)
        self.saveFormatLabel = QtWidgets.QLabel(self.saveGroupBox)
        self.saveFormatLabel.setObjectName("saveFormatLabel")
        self.gridLayout_2.addWidget(self.saveFormatLabel, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveDirectoryPushButton = QtWidgets.QPushButton(self.saveGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDirectoryPushButton.sizePolicy().hasHeightForWidth())
        self.saveDirectoryPushButton.setSizePolicy(sizePolicy)
        self.saveDirectoryPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveDirectoryPushButton.setStyleSheet("QPushButton { text-align: left; }")
        self.saveDirectoryPushButton.setObjectName("saveDirectoryPushButton")
        self.horizontalLayout_6.addWidget(self.saveDirectoryPushButton)
        self.saveDirectoryBrowseToolButton = QtWidgets.QToolButton(self.saveGroupBox)
        self.saveDirectoryBrowseToolButton.setIconSize(QtCore.QSize(16, 16))
        self.saveDirectoryBrowseToolButton.setObjectName("saveDirectoryBrowseToolButton")
        self.horizontalLayout_6.addWidget(self.saveDirectoryBrowseToolButton)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_6.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.widget_6 = QtWidgets.QWidget(self.saveGroupBox)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.savePushButton = QtWidgets.QPushButton(self.widget_6)
        self.savePushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.savePushButton.setCheckable(False)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_8.addWidget(self.savePushButton)
        self.saveStatusLabel = QtWidgets.QLabel(self.widget_6)
        self.saveStatusLabel.setObjectName("saveStatusLabel")
        self.horizontalLayout_8.addWidget(self.saveStatusLabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.horizontalLayout.addWidget(self.saveGroupBox)
        self.verticalLayout.addWidget(self.topFrame)
        self.selectionTableFrame = QtWidgets.QFrame(WaveformDialog)
        self.selectionTableFrame.setObjectName("selectionTableFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.selectionTableFrame)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filterGroupBox = QtWidgets.QGroupBox(self.selectionTableFrame)
        self.filterGroupBox.setEnabled(True)
        self.filterGroupBox.setObjectName("filterGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.filterGroupBox)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hideNoDataCheckBox = QtWidgets.QCheckBox(self.filterGroupBox)
        self.hideNoDataCheckBox.setObjectName("hideNoDataCheckBox")
        self.horizontalLayout_2.addWidget(self.hideNoDataCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.eventComboBox = QtWidgets.QComboBox(self.filterGroupBox)
        self.eventComboBox.setObjectName("eventComboBox")
        self.horizontalLayout_2.addWidget(self.eventComboBox)
        self.networkComboBox = QtWidgets.QComboBox(self.filterGroupBox)
        self.networkComboBox.setObjectName("networkComboBox")
        self.horizontalLayout_2.addWidget(self.networkComboBox)
        self.stationComboBox = QtWidgets.QComboBox(self.filterGroupBox)
        self.stationComboBox.setObjectName("stationComboBox")
        self.horizontalLayout_2.addWidget(self.stationComboBox)
        self.horizontalLayout_2.setStretch(2, 3)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.addWidget(self.filterGroupBox)
        self.selectionTable = QtWidgets.QTableWidget(self.selectionTableFrame)
        self.selectionTable.setMinimumSize(QtCore.QSize(500, 100))
        self.selectionTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.selectionTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.selectionTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.selectionTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.selectionTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.selectionTable.setShowGrid(False)
        self.selectionTable.setObjectName("selectionTable")
        self.selectionTable.setColumnCount(0)
        self.selectionTable.setRowCount(0)
        self.selectionTable.horizontalHeader().setStretchLastSection(False)
        self.selectionTable.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.selectionTable)
        self.verticalLayout.addWidget(self.selectionTableFrame)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(WaveformDialog)
        QtCore.QMetaObject.connectSlotsByName(WaveformDialog)

    def retranslateUi(self, WaveformDialog):
        _translate = QtCore.QCoreApplication.translate
        WaveformDialog.setWindowTitle(_translate("WaveformDialog", "Dialog"))
        self.downloadGroupBox.setTitle(_translate("WaveformDialog", "Download / Preview Waveforms"))
        self.secondsBeforeLabel.setText(_translate("WaveformDialog", "Start:"))
        self.label.setText(_translate("WaveformDialog", "secs before"))
        self.label_2.setText(_translate("WaveformDialog", "secs after"))
        self.secondsAfterLabel.setText(_translate("WaveformDialog", "End:"))
        self.downloadPushButton.setText(_translate("WaveformDialog", "Download"))
        self.downloadStatusLabel.setText(_translate("WaveformDialog", "Download status"))
        self.saveGroupBox.setTitle(_translate("WaveformDialog", "Save Waveforms"))
        self.sacUseEventTimeCheckBox.setToolTip(_translate("WaveformDialog", "For SAC output, use the event time as the origin (iztype=\"io\")"))
        self.sacUseEventTimeCheckBox.setText(_translate("WaveformDialog", "Use event time"))
        self.saveDirectoryLabel.setText(_translate("WaveformDialog", "To:"))
        self.saveFormatLabel.setText(_translate("WaveformDialog", "As:"))
        self.saveDirectoryPushButton.setText(_translate("WaveformDialog", "Directory"))
        self.saveDirectoryBrowseToolButton.setText(_translate("WaveformDialog", "Open"))
        self.savePushButton.setText(_translate("WaveformDialog", "Save"))
        self.saveStatusLabel.setText(_translate("WaveformDialog", "Save status"))
        self.filterGroupBox.setTitle(_translate("WaveformDialog", "Table Filters"))
        self.hideNoDataCheckBox.setToolTip(_translate("WaveformDialog", "Hide rows when no data is found"))
        self.hideNoDataCheckBox.setText(_translate("WaveformDialog", "Hide no data"))
        self.selectionTable.setSortingEnabled(True)

