# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventOptionsDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventOptionsDialog(object):
    def setupUi(self, EventOptionsDialog):
        EventOptionsDialog.setObjectName(_fromUtf8("EventOptionsDialog"))
        EventOptionsDialog.resize(320, 520)
        EventOptionsDialog.setMinimumSize(QtCore.QSize(320, 520))
        self.verticalLayout = QtGui.QVBoxLayout(EventOptionsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timeGroupBox = QtGui.QGroupBox(EventOptionsDialog)
        self.timeGroupBox.setStyleSheet(_fromUtf8(""))
        self.timeGroupBox.setObjectName(_fromUtf8("timeGroupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.timeGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.endtimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        self.endtimeDateTimeEdit.setObjectName(_fromUtf8("endtimeDateTimeEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.endtimeDateTimeEdit)
        self.endtimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.endtimeLabel.setObjectName(_fromUtf8("endtimeLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.endtimeLabel)
        self.starttimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        self.starttimeDateTimeEdit.setObjectName(_fromUtf8("starttimeDateTimeEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.starttimeDateTimeEdit)
        self.starttimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.starttimeLabel.setObjectName(_fromUtf8("starttimeLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.starttimeLabel)
        self.verticalLayout.addWidget(self.timeGroupBox)
        self.magDepthGroupBox = QtGui.QGroupBox(EventOptionsDialog)
        self.magDepthGroupBox.setObjectName(_fromUtf8("magDepthGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.magDepthGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maxdepthLineEdit = QtGui.QLineEdit(self.magDepthGroupBox)
        self.maxdepthLineEdit.setText(_fromUtf8(""))
        self.maxdepthLineEdit.setObjectName(_fromUtf8("maxdepthLineEdit"))
        self.gridLayout.addWidget(self.maxdepthLineEdit, 6, 2, 1, 1)
        self.depthLabel = QtGui.QLabel(self.magDepthGroupBox)
        self.depthLabel.setObjectName(_fromUtf8("depthLabel"))
        self.gridLayout.addWidget(self.depthLabel, 6, 0, 1, 1)
        self.minmagLineEdit = QtGui.QLineEdit(self.magDepthGroupBox)
        self.minmagLineEdit.setText(_fromUtf8(""))
        self.minmagLineEdit.setObjectName(_fromUtf8("minmagLineEdit"))
        self.gridLayout.addWidget(self.minmagLineEdit, 2, 1, 1, 1)
        self.mindepthLineEdit = QtGui.QLineEdit(self.magDepthGroupBox)
        self.mindepthLineEdit.setText(_fromUtf8(""))
        self.mindepthLineEdit.setObjectName(_fromUtf8("mindepthLineEdit"))
        self.gridLayout.addWidget(self.mindepthLineEdit, 6, 1, 1, 1)
        self.maximumLabel = QtGui.QLabel(self.magDepthGroupBox)
        self.maximumLabel.setObjectName(_fromUtf8("maximumLabel"))
        self.gridLayout.addWidget(self.maximumLabel, 1, 2, 1, 1)
        self.minimumLabel = QtGui.QLabel(self.magDepthGroupBox)
        self.minimumLabel.setObjectName(_fromUtf8("minimumLabel"))
        self.gridLayout.addWidget(self.minimumLabel, 1, 1, 1, 1)
        self.magnitudeLabel = QtGui.QLabel(self.magDepthGroupBox)
        self.magnitudeLabel.setObjectName(_fromUtf8("magnitudeLabel"))
        self.gridLayout.addWidget(self.magnitudeLabel, 2, 0, 1, 1)
        self.maxmagLineEdit = QtGui.QLineEdit(self.magDepthGroupBox)
        self.maxmagLineEdit.setText(_fromUtf8(""))
        self.maxmagLineEdit.setObjectName(_fromUtf8("maxmagLineEdit"))
        self.gridLayout.addWidget(self.maxmagLineEdit, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.magDepthGroupBox)
        self.catalogTypeGroupBox = QtGui.QGroupBox(EventOptionsDialog)
        self.catalogTypeGroupBox.setObjectName(_fromUtf8("catalogTypeGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.catalogTypeGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.catalogComboBox = QtGui.QComboBox(self.catalogTypeGroupBox)
        self.catalogComboBox.setObjectName(_fromUtf8("catalogComboBox"))
        self.catalogComboBox.addItem(_fromUtf8(""))
        self.catalogComboBox.addItem(_fromUtf8(""))
        self.catalogComboBox.addItem(_fromUtf8(""))
        self.catalogComboBox.addItem(_fromUtf8(""))
        self.catalogComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.catalogComboBox, 1, 0, 1, 1)
        self.typeComboBox = QtGui.QComboBox(self.catalogTypeGroupBox)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.typeComboBox, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.catalogTypeGroupBox)
        self.locationGroupBox = QtGui.QGroupBox(EventOptionsDialog)
        self.locationGroupBox.setObjectName(_fromUtf8("locationGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.locationGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.minlonLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.minlonLineEdit.setObjectName(_fromUtf8("minlonLineEdit"))
        self.gridLayout_3.addWidget(self.minlonLineEdit, 2, 0, 1, 1)
        self.maxlonLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.maxlonLineEdit.setObjectName(_fromUtf8("maxlonLineEdit"))
        self.gridLayout_3.addWidget(self.maxlonLineEdit, 2, 2, 1, 1)
        self.centerLabel = QtGui.QLabel(self.locationGroupBox)
        self.centerLabel.setObjectName(_fromUtf8("centerLabel"))
        self.gridLayout_3.addWidget(self.centerLabel, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.maxlatLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.maxlatLineEdit.setObjectName(_fromUtf8("maxlatLineEdit"))
        self.gridLayout_3.addWidget(self.maxlatLineEdit, 0, 1, 1, 1)
        self.minlatLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.minlatLineEdit.setObjectName(_fromUtf8("minlatLineEdit"))
        self.gridLayout_3.addWidget(self.minlatLineEdit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.locationGroupBox)
        self.closeButton = QtGui.QPushButton(EventOptionsDialog)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.verticalLayout.addWidget(self.closeButton)

        self.retranslateUi(EventOptionsDialog)
        QtCore.QMetaObject.connectSlotsByName(EventOptionsDialog)

    def retranslateUi(self, EventOptionsDialog):
        EventOptionsDialog.setWindowTitle(_translate("EventOptionsDialog", "Dialog", None))
        self.timeGroupBox.setTitle(_translate("EventOptionsDialog", "Event Time Interval", None))
        self.endtimeLabel.setText(_translate("EventOptionsDialog", "End Time", None))
        self.starttimeLabel.setText(_translate("EventOptionsDialog", "Start Time", None))
        self.magDepthGroupBox.setTitle(_translate("EventOptionsDialog", "Magnitude and Depth", None))
        self.depthLabel.setText(_translate("EventOptionsDialog", "Depth", None))
        self.maximumLabel.setText(_translate("EventOptionsDialog", "Maximum", None))
        self.minimumLabel.setText(_translate("EventOptionsDialog", "Minimum", None))
        self.magnitudeLabel.setText(_translate("EventOptionsDialog", "Magnitude", None))
        self.catalogTypeGroupBox.setTitle(_translate("EventOptionsDialog", "Catalog and Type", None))
        self.catalogComboBox.setItemText(0, _translate("EventOptionsDialog", "All Catalogs", None))
        self.catalogComboBox.setItemText(1, _translate("EventOptionsDialog", "ANF", None))
        self.catalogComboBox.setItemText(2, _translate("EventOptionsDialog", "GCMT", None))
        self.catalogComboBox.setItemText(3, _translate("EventOptionsDialog", "NEIC PDE", None))
        self.catalogComboBox.setItemText(4, _translate("EventOptionsDialog", "ISC", None))
        self.typeComboBox.setItemText(0, _translate("EventOptionsDialog", "All Types", None))
        self.typeComboBox.setItemText(1, _translate("EventOptionsDialog", "MB", None))
        self.typeComboBox.setItemText(2, _translate("EventOptionsDialog", "ML", None))
        self.typeComboBox.setItemText(3, _translate("EventOptionsDialog", "MS", None))
        self.typeComboBox.setItemText(4, _translate("EventOptionsDialog", "MW", None))
        self.locationGroupBox.setTitle(_translate("EventOptionsDialog", "Location Box", None))
        self.centerLabel.setText(_translate("EventOptionsDialog", "Location", None))
        self.closeButton.setText(_translate("EventOptionsDialog", "Close Window", None))

