# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StationQueryDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationQueryDialog(object):
    def setupUi(self, StationQueryDialog):
        StationQueryDialog.setObjectName(_fromUtf8("StationQueryDialog"))
        self.verticalLayout = QtGui.QVBoxLayout(StationQueryDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SNCLGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.SNCLGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SNCLGroupBox.setObjectName(_fromUtf8("SNCLGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.SNCLGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.channelLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.channelLabel.setObjectName(_fromUtf8("channelLabel"))
        self.gridLayout_2.addWidget(self.channelLabel, 0, 3, 1, 1)
        self.locationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.gridLayout_2.addWidget(self.locationLabel, 0, 2, 1, 1)
        self.channelLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelLineEdit.sizePolicy().hasHeightForWidth())
        self.channelLineEdit.setSizePolicy(sizePolicy)
        self.channelLineEdit.setObjectName(_fromUtf8("channelLineEdit"))
        self.gridLayout_2.addWidget(self.channelLineEdit, 1, 3, 1, 1)
        self.locationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.locationLineEdit.setObjectName(_fromUtf8("locationLineEdit"))
        self.gridLayout_2.addWidget(self.locationLineEdit, 1, 2, 1, 1)
        self.networkLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.networkLabel.setObjectName(_fromUtf8("networkLabel"))
        self.gridLayout_2.addWidget(self.networkLabel, 0, 0, 1, 1)
        self.networkLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.networkLineEdit.setObjectName(_fromUtf8("networkLineEdit"))
        self.gridLayout_2.addWidget(self.networkLineEdit, 1, 0, 1, 1)
        self.stationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.stationLabel.setObjectName(_fromUtf8("stationLabel"))
        self.gridLayout_2.addWidget(self.stationLabel, 0, 1, 1, 1)
        self.stationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.stationLineEdit.setObjectName(_fromUtf8("stationLineEdit"))
        self.gridLayout_2.addWidget(self.stationLineEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.SNCLGroupBox)
        self.timeGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.timeGroupBox.setObjectName(_fromUtf8("timeGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.timeGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.timeBetweenRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeBetweenRadioButton.setEnabled(True)
        self.timeBetweenRadioButton.setChecked(True)
        self.timeBetweenRadioButton.setObjectName(_fromUtf8("timeBetweenRadioButton"))
        self.verticalLayout_10.addWidget(self.timeBetweenRadioButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.starttimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.starttimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.starttimeLabel.setObjectName(_fromUtf8("starttimeLabel"))
        self.horizontalLayout_3.addWidget(self.starttimeLabel)
        self.starttimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        self.starttimeDateTimeEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.starttimeDateTimeEdit.setCalendarPopup(True)
        self.starttimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeDateTimeEdit.setObjectName(_fromUtf8("starttimeDateTimeEdit"))
        self.horizontalLayout_3.addWidget(self.starttimeDateTimeEdit)
        self.endtimeLabele = QtGui.QLabel(self.timeGroupBox)
        self.endtimeLabele.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endtimeLabele.setObjectName(_fromUtf8("endtimeLabele"))
        self.horizontalLayout_3.addWidget(self.endtimeLabele)
        self.endtimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endtimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.endtimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.endtimeDateTimeEdit.setProperty("showGroupSeparator", False)
        self.endtimeDateTimeEdit.setCalendarPopup(True)
        self.endtimeDateTimeEdit.setCurrentSectionIndex(1)
        self.endtimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endtimeDateTimeEdit.setObjectName(_fromUtf8("endtimeDateTimeEdit"))
        self.horizontalLayout_3.addWidget(self.endtimeDateTimeEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.timeDuringEventsRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeDuringEventsRadioButton.setObjectName(_fromUtf8("timeDuringEventsRadioButton"))
        self.verticalLayout_2.addWidget(self.timeDuringEventsRadioButton)
        self.verticalLayout_3.addWidget(self.timeGroupBox)
        self.locationGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.locationGroupBox.setMinimumSize(QtCore.QSize(0, 375))
        self.locationGroupBox.setObjectName(_fromUtf8("locationGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.locationGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.locationRangeRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationRangeRadioButton.setChecked(True)
        self.locationRangeRadioButton.setObjectName(_fromUtf8("locationRangeRadioButton"))
        self.verticalLayout_6.addWidget(self.locationRangeRadioButton)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.locationRangeNorthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeNorthLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeNorthLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeNorthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.locationRangeNorthLineEdit.setObjectName(_fromUtf8("locationRangeNorthLineEdit"))
        self.horizontalLayout_4.addWidget(self.locationRangeNorthLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.locationRangeEastLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeEastLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeEastLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeEastLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.locationRangeEastLineEdit.setObjectName(_fromUtf8("locationRangeEastLineEdit"))
        self.horizontalLayout.addWidget(self.locationRangeEastLineEdit)
        self.locationRangeWestLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeWestLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeWestLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeWestLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.locationRangeWestLineEdit.setObjectName(_fromUtf8("locationRangeWestLineEdit"))
        self.horizontalLayout.addWidget(self.locationRangeWestLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.locationRangeSouthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeSouthLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeSouthLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeSouthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.locationRangeSouthLineEdit.setObjectName(_fromUtf8("locationRangeSouthLineEdit"))
        self.horizontalLayout_5.addWidget(self.locationRangeSouthLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.locationDistanceFromPointRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromPointRadioButton.setEnabled(True)
        self.locationDistanceFromPointRadioButton.setObjectName(_fromUtf8("locationDistanceFromPointRadioButton"))
        self.verticalLayout_7.addWidget(self.locationDistanceFromPointRadioButton)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.distanceFromPointMinRadiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointMinRadiusLineEdit.setEnabled(True)
        self.distanceFromPointMinRadiusLineEdit.setObjectName(_fromUtf8("distanceFromPointMinRadiusLineEdit"))
        self.horizontalLayout_6.addWidget(self.distanceFromPointMinRadiusLineEdit)
        self.label_10 = QtGui.QLabel(self.locationGroupBox)
        self.label_10.setEnabled(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.distanceFromPointMaxRadiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointMaxRadiusLineEdit.setEnabled(True)
        self.distanceFromPointMaxRadiusLineEdit.setObjectName(_fromUtf8("distanceFromPointMaxRadiusLineEdit"))
        self.horizontalLayout_6.addWidget(self.distanceFromPointMaxRadiusLineEdit)
        self.label_11 = QtGui.QLabel(self.locationGroupBox)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.locationGroupBox)
        self.label_6.setEnabled(True)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.distanceFromPointEastLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointEastLineEdit.setEnabled(True)
        self.distanceFromPointEastLineEdit.setObjectName(_fromUtf8("distanceFromPointEastLineEdit"))
        self.horizontalLayout_7.addWidget(self.distanceFromPointEastLineEdit)
        self.label_8 = QtGui.QLabel(self.locationGroupBox)
        self.label_8.setEnabled(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.distanceFromPointNorthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointNorthLineEdit.setEnabled(True)
        self.distanceFromPointNorthLineEdit.setObjectName(_fromUtf8("distanceFromPointNorthLineEdit"))
        self.horizontalLayout_7.addWidget(self.distanceFromPointNorthLineEdit)
        self.label_9 = QtGui.QLabel(self.locationGroupBox)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.locationDistanceFromEventsRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromEventsRadioButton.setEnabled(False)
        self.locationDistanceFromEventsRadioButton.setObjectName(_fromUtf8("locationDistanceFromEventsRadioButton"))
        self.verticalLayout_9.addWidget(self.locationDistanceFromEventsRadioButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.distanceFromEventsMinradiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromEventsMinradiusLineEdit.setEnabled(False)
        self.distanceFromEventsMinradiusLineEdit.setObjectName(_fromUtf8("distanceFromEventsMinradiusLineEdit"))
        self.horizontalLayout_2.addWidget(self.distanceFromEventsMinradiusLineEdit)
        self.label_3 = QtGui.QLabel(self.locationGroupBox)
        self.label_3.setEnabled(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.distanceFromEventsMaxradiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromEventsMaxradiusLineEdit.setEnabled(False)
        self.distanceFromEventsMaxradiusLineEdit.setObjectName(_fromUtf8("distanceFromEventsMaxradiusLineEdit"))
        self.horizontalLayout_2.addWidget(self.distanceFromEventsMaxradiusLineEdit)
        self.label_5 = QtGui.QLabel(self.locationGroupBox)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_3.addWidget(self.locationGroupBox)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(StationQueryDialog)
        QtCore.QMetaObject.connectSlotsByName(StationQueryDialog)
        StationQueryDialog.setTabOrder(self.timeDuringEventsRadioButton, self.distanceFromPointMinRadiusLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointMinRadiusLineEdit, self.distanceFromPointMaxRadiusLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointMaxRadiusLineEdit, self.distanceFromPointNorthLineEdit)

    def retranslateUi(self, StationQueryDialog):
        StationQueryDialog.setWindowTitle(_translate("StationQueryDialog", "Dialog", None))
        self.SNCLGroupBox.setTitle(_translate("StationQueryDialog", "SNCL", None))
        self.channelLabel.setText(_translate("StationQueryDialog", "Channels", None))
        self.locationLabel.setText(_translate("StationQueryDialog", "Locations", None))
        self.channelLineEdit.setText(_translate("StationQueryDialog", "?HZ", None))
        self.locationLineEdit.setText(_translate("StationQueryDialog", "*", None))
        self.networkLabel.setText(_translate("StationQueryDialog", "Networks", None))
        self.networkLineEdit.setText(_translate("StationQueryDialog", "_GSN", None))
        self.stationLabel.setText(_translate("StationQueryDialog", "Stations", None))
        self.stationLineEdit.setText(_translate("StationQueryDialog", "*", None))
        self.timeGroupBox.setTitle(_translate("StationQueryDialog", "Time", None))
        self.timeBetweenRadioButton.setText(_translate("StationQueryDialog", "Between start and end times", None))
        self.starttimeLabel.setText(_translate("StationQueryDialog", "start", None))
        self.starttimeDateTimeEdit.setDisplayFormat(_translate("StationQueryDialog", "yyyy/dd/MM HH:mm:ss", None))
        self.endtimeLabele.setText(_translate("StationQueryDialog", "end", None))
        self.endtimeDateTimeEdit.setDisplayFormat(_translate("StationQueryDialog", "yyyy-dd-MM HH:mm:ss", None))
        self.timeDuringEventsRadioButton.setText(_translate("StationQueryDialog", "Operational during selected events", None))
        self.locationGroupBox.setTitle(_translate("StationQueryDialog", "Location", None))
        self.locationRangeRadioButton.setText(_translate("StationQueryDialog", "Within lat/lon box", None))
        self.locationDistanceFromPointRadioButton.setText(_translate("StationQueryDialog", "Distance from point", None))
        self.label_10.setText(_translate("StationQueryDialog", "-", None))
        self.label_11.setText(_translate("StationQueryDialog", "degrees", None))
        self.label_6.setText(_translate("StationQueryDialog", "from", None))
        self.label_8.setText(_translate("StationQueryDialog", "E", None))
        self.label_9.setText(_translate("StationQueryDialog", "N", None))
        self.locationDistanceFromEventsRadioButton.setText(_translate("StationQueryDialog", "Distance from selected events", None))
        self.label_3.setText(_translate("StationQueryDialog", "-", None))
        self.label_5.setText(_translate("StationQueryDialog", "degrees", None))

