# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StationQueryDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationQueryDialog(object):
    def setupUi(self, StationQueryDialog):
        StationQueryDialog.setObjectName(_fromUtf8("StationQueryDialog"))
        self.verticalLayout = QtGui.QVBoxLayout(StationQueryDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.SNCLGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.SNCLGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SNCLGroupBox.setObjectName(_fromUtf8("SNCLGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.SNCLGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.networkLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.networkLabel.setObjectName(_fromUtf8("networkLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.networkLabel)
        self.networkLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.networkLineEdit.setObjectName(_fromUtf8("networkLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.networkLineEdit)
        self.stationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.stationLineEdit.setObjectName(_fromUtf8("stationLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.stationLineEdit)
        self.locationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.locationLabel)
        self.locationLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        self.locationLineEdit.setObjectName(_fromUtf8("locationLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.locationLineEdit)
        self.channelLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.channelLabel.setObjectName(_fromUtf8("channelLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.channelLabel)
        self.channelLineEdit = QtGui.QLineEdit(self.SNCLGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelLineEdit.sizePolicy().hasHeightForWidth())
        self.channelLineEdit.setSizePolicy(sizePolicy)
        self.channelLineEdit.setObjectName(_fromUtf8("channelLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.channelLineEdit)
        self.stationLabel = QtGui.QLabel(self.SNCLGroupBox)
        self.stationLabel.setObjectName(_fromUtf8("stationLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.stationLabel)
        self.horizontalLayout_13.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.SNCLGroupBox)
        self.timeGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.timeGroupBox.setObjectName(_fromUtf8("timeGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.timeGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.timeBetweenRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeBetweenRadioButton.setEnabled(True)
        self.timeBetweenRadioButton.setChecked(True)
        self.timeBetweenRadioButton.setObjectName(_fromUtf8("timeBetweenRadioButton"))
        self.verticalLayout_2.addWidget(self.timeBetweenRadioButton)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.starttimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        self.starttimeDateTimeEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.starttimeDateTimeEdit.setCalendarPopup(True)
        self.starttimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeDateTimeEdit.setObjectName(_fromUtf8("starttimeDateTimeEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.starttimeDateTimeEdit)
        self.endtimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.endtimeLabel.setObjectName(_fromUtf8("endtimeLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.endtimeLabel)
        self.endtimeDateTimeEdit = QtGui.QDateTimeEdit(self.timeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endtimeDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.endtimeDateTimeEdit.setSizePolicy(sizePolicy)
        self.endtimeDateTimeEdit.setProperty("showGroupSeparator", False)
        self.endtimeDateTimeEdit.setCalendarPopup(True)
        self.endtimeDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endtimeDateTimeEdit.setObjectName(_fromUtf8("endtimeDateTimeEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.endtimeDateTimeEdit)
        self.starttimeLabel = QtGui.QLabel(self.timeGroupBox)
        self.starttimeLabel.setObjectName(_fromUtf8("starttimeLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.starttimeLabel)
        self.horizontalLayout_10.addLayout(self.formLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.timeDuringEventsRadioButton = QtGui.QRadioButton(self.timeGroupBox)
        self.timeDuringEventsRadioButton.setObjectName(_fromUtf8("timeDuringEventsRadioButton"))
        self.verticalLayout_2.addWidget(self.timeDuringEventsRadioButton)
        self.verticalLayout.addWidget(self.timeGroupBox)
        self.locationGroupBox = QtGui.QGroupBox(StationQueryDialog)
        self.locationGroupBox.setObjectName(_fromUtf8("locationGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.locationGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.locationRangeRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationRangeRadioButton.setChecked(True)
        self.locationRangeRadioButton.setObjectName(_fromUtf8("locationRangeRadioButton"))
        self.verticalLayout_4.addWidget(self.locationRangeRadioButton)
        self.locationRangeLayout = QtGui.QHBoxLayout()
        self.locationRangeLayout.setContentsMargins(24, -1, -1, -1)
        self.locationRangeLayout.setSpacing(0)
        self.locationRangeLayout.setObjectName(_fromUtf8("locationRangeLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.locationRangeNorthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeNorthLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeNorthLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeNorthLineEdit.setObjectName(_fromUtf8("locationRangeNorthLineEdit"))
        self.horizontalLayout_4.addWidget(self.locationRangeNorthLineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.locationRangeEastLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeEastLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeEastLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeEastLineEdit.setObjectName(_fromUtf8("locationRangeEastLineEdit"))
        self.horizontalLayout.addWidget(self.locationRangeEastLineEdit)
        self.locationRangeWestLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeWestLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeWestLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeWestLineEdit.setObjectName(_fromUtf8("locationRangeWestLineEdit"))
        self.horizontalLayout.addWidget(self.locationRangeWestLineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.locationRangeSouthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationRangeSouthLineEdit.sizePolicy().hasHeightForWidth())
        self.locationRangeSouthLineEdit.setSizePolicy(sizePolicy)
        self.locationRangeSouthLineEdit.setObjectName(_fromUtf8("locationRangeSouthLineEdit"))
        self.horizontalLayout_5.addWidget(self.locationRangeSouthLineEdit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.locationRangeLayout.addLayout(self.verticalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.locationRangeLayout.addItem(spacerItem6)
        self.locationRangeLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.locationRangeLayout)
        self.locationDistanceFromPointRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromPointRadioButton.setEnabled(True)
        self.locationDistanceFromPointRadioButton.setObjectName(_fromUtf8("locationDistanceFromPointRadioButton"))
        self.verticalLayout_4.addWidget(self.locationDistanceFromPointRadioButton)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.locationGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.distanceFromPointMinRadiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointMinRadiusLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromPointMinRadiusLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromPointMinRadiusLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromPointMinRadiusLineEdit.setObjectName(_fromUtf8("distanceFromPointMinRadiusLineEdit"))
        self.horizontalLayout_6.addWidget(self.distanceFromPointMinRadiusLineEdit)
        self.label_11 = QtGui.QLabel(self.locationGroupBox)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_2 = QtGui.QLabel(self.locationGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.distanceFromPointMaxRadiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointMaxRadiusLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromPointMaxRadiusLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromPointMaxRadiusLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromPointMaxRadiusLineEdit.setObjectName(_fromUtf8("distanceFromPointMaxRadiusLineEdit"))
        self.horizontalLayout_3.addWidget(self.distanceFromPointMaxRadiusLineEdit)
        self.label_10 = QtGui.QLabel(self.locationGroupBox)
        self.label_10.setEnabled(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_6 = QtGui.QLabel(self.locationGroupBox)
        self.label_6.setEnabled(True)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.distanceFromPointEastLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointEastLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromPointEastLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromPointEastLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromPointEastLineEdit.setObjectName(_fromUtf8("distanceFromPointEastLineEdit"))
        self.horizontalLayout_7.addWidget(self.distanceFromPointEastLineEdit)
        self.label_4 = QtGui.QLabel(self.locationGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_8 = QtGui.QLabel(self.locationGroupBox)
        self.label_8.setEnabled(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.distanceFromPointNorthLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromPointNorthLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromPointNorthLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromPointNorthLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromPointNorthLineEdit.setObjectName(_fromUtf8("distanceFromPointNorthLineEdit"))
        self.horizontalLayout_8.addWidget(self.distanceFromPointNorthLineEdit)
        self.label_7 = QtGui.QLabel(self.locationGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.formLayout_3.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.formLayout_3)
        spacerItem7 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.locationDistanceFromEventsRadioButton = QtGui.QRadioButton(self.locationGroupBox)
        self.locationDistanceFromEventsRadioButton.setEnabled(False)
        self.locationDistanceFromEventsRadioButton.setObjectName(_fromUtf8("locationDistanceFromEventsRadioButton"))
        self.verticalLayout_4.addWidget(self.locationDistanceFromEventsRadioButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_9 = QtGui.QLabel(self.locationGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.distanceFromEventsMinradiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromEventsMinradiusLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromEventsMinradiusLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromEventsMinradiusLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromEventsMinradiusLineEdit.setObjectName(_fromUtf8("distanceFromEventsMinradiusLineEdit"))
        self.horizontalLayout_11.addWidget(self.distanceFromEventsMinradiusLineEdit)
        self.label_3 = QtGui.QLabel(self.locationGroupBox)
        self.label_3.setEnabled(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_12 = QtGui.QLabel(self.locationGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.distanceFromEventsMaxradiusLineEdit = QtGui.QLineEdit(self.locationGroupBox)
        self.distanceFromEventsMaxradiusLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceFromEventsMaxradiusLineEdit.sizePolicy().hasHeightForWidth())
        self.distanceFromEventsMaxradiusLineEdit.setSizePolicy(sizePolicy)
        self.distanceFromEventsMaxradiusLineEdit.setObjectName(_fromUtf8("distanceFromEventsMaxradiusLineEdit"))
        self.horizontalLayout_12.addWidget(self.distanceFromEventsMaxradiusLineEdit)
        self.label_5 = QtGui.QLabel(self.locationGroupBox)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.locationGroupBox)

        self.retranslateUi(StationQueryDialog)
        QtCore.QMetaObject.connectSlotsByName(StationQueryDialog)
        StationQueryDialog.setTabOrder(self.networkLineEdit, self.stationLineEdit)
        StationQueryDialog.setTabOrder(self.stationLineEdit, self.locationLineEdit)
        StationQueryDialog.setTabOrder(self.locationLineEdit, self.channelLineEdit)
        StationQueryDialog.setTabOrder(self.channelLineEdit, self.timeBetweenRadioButton)
        StationQueryDialog.setTabOrder(self.timeBetweenRadioButton, self.starttimeDateTimeEdit)
        StationQueryDialog.setTabOrder(self.starttimeDateTimeEdit, self.endtimeDateTimeEdit)
        StationQueryDialog.setTabOrder(self.endtimeDateTimeEdit, self.timeDuringEventsRadioButton)
        StationQueryDialog.setTabOrder(self.timeDuringEventsRadioButton, self.locationRangeRadioButton)
        StationQueryDialog.setTabOrder(self.locationRangeRadioButton, self.locationRangeNorthLineEdit)
        StationQueryDialog.setTabOrder(self.locationRangeNorthLineEdit, self.locationRangeEastLineEdit)
        StationQueryDialog.setTabOrder(self.locationRangeEastLineEdit, self.locationRangeWestLineEdit)
        StationQueryDialog.setTabOrder(self.locationRangeWestLineEdit, self.locationRangeSouthLineEdit)
        StationQueryDialog.setTabOrder(self.locationRangeSouthLineEdit, self.locationDistanceFromPointRadioButton)
        StationQueryDialog.setTabOrder(self.locationDistanceFromPointRadioButton, self.distanceFromPointMinRadiusLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointMinRadiusLineEdit, self.distanceFromPointMaxRadiusLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointMaxRadiusLineEdit, self.distanceFromPointEastLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointEastLineEdit, self.distanceFromPointNorthLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromPointNorthLineEdit, self.locationDistanceFromEventsRadioButton)
        StationQueryDialog.setTabOrder(self.locationDistanceFromEventsRadioButton, self.distanceFromEventsMinradiusLineEdit)
        StationQueryDialog.setTabOrder(self.distanceFromEventsMinradiusLineEdit, self.distanceFromEventsMaxradiusLineEdit)

    def retranslateUi(self, StationQueryDialog):
        StationQueryDialog.setWindowTitle(_translate("StationQueryDialog", "Dialog", None))
        self.SNCLGroupBox.setTitle(_translate("StationQueryDialog", "SNCL", None))
        self.networkLabel.setText(_translate("StationQueryDialog", "Networks", None))
        self.networkLineEdit.setText(_translate("StationQueryDialog", "_GSN", None))
        self.stationLineEdit.setText(_translate("StationQueryDialog", "*", None))
        self.locationLabel.setText(_translate("StationQueryDialog", "Locations", None))
        self.locationLineEdit.setText(_translate("StationQueryDialog", "*", None))
        self.channelLabel.setText(_translate("StationQueryDialog", "Channels", None))
        self.channelLineEdit.setText(_translate("StationQueryDialog", "?HZ", None))
        self.stationLabel.setText(_translate("StationQueryDialog", "Stations", None))
        self.timeGroupBox.setTitle(_translate("StationQueryDialog", "Time", None))
        self.timeBetweenRadioButton.setText(_translate("StationQueryDialog", "Between start and end times", None))
        self.starttimeDateTimeEdit.setDisplayFormat(_translate("StationQueryDialog", "yyyy-MM-dd hh:mm:ss", None))
        self.endtimeLabel.setText(_translate("StationQueryDialog", "end", None))
        self.endtimeDateTimeEdit.setDisplayFormat(_translate("StationQueryDialog", "yyyy-MM-dd hh:mm:ss", None))
        self.starttimeLabel.setText(_translate("StationQueryDialog", "start", None))
        self.timeDuringEventsRadioButton.setText(_translate("StationQueryDialog", "Operational during selected events", None))
        self.locationGroupBox.setTitle(_translate("StationQueryDialog", "Location", None))
        self.locationRangeRadioButton.setText(_translate("StationQueryDialog", "Within lat/lon box", None))
        self.locationRangeNorthLineEdit.setPlaceholderText(_translate("StationQueryDialog", "Max Latitude", None))
        self.locationDistanceFromPointRadioButton.setText(_translate("StationQueryDialog", "Distance from point", None))
        self.label.setText(_translate("StationQueryDialog", "between", None))
        self.label_11.setText(_translate("StationQueryDialog", "degrees", None))
        self.label_2.setText(_translate("StationQueryDialog", "and", None))
        self.label_10.setText(_translate("StationQueryDialog", "degrees", None))
        self.label_6.setText(_translate("StationQueryDialog", "from", None))
        self.label_4.setText(_translate("StationQueryDialog", "E", None))
        self.label_8.setText(_translate("StationQueryDialog", "and", None))
        self.label_7.setText(_translate("StationQueryDialog", "N", None))
        self.locationDistanceFromEventsRadioButton.setText(_translate("StationQueryDialog", "Distance from selected events", None))
        self.label_9.setText(_translate("StationQueryDialog", "between", None))
        self.label_3.setText(_translate("StationQueryDialog", "degrees", None))
        self.label_12.setText(_translate("StationQueryDialog", "and", None))
        self.label_5.setText(_translate("StationQueryDialog", "degrees", None))

