# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaveformDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WaveformDialog(object):
    def setupUi(self, WaveformDialog):
        WaveformDialog.setObjectName(_fromUtf8("WaveformDialog"))
        WaveformDialog.resize(1240, 1103)
        self.verticalLayout = QtGui.QVBoxLayout(WaveformDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topFrame = QtGui.QFrame(WaveformDialog)
        self.topFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.topFrame.setObjectName(_fromUtf8("topFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.downloadButtonGroupBox = QtGui.QGroupBox(self.topFrame)
        self.downloadButtonGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.downloadButtonGroupBox.setObjectName(_fromUtf8("downloadButtonGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.downloadButtonGroupBox)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_5 = QtGui.QWidget(self.downloadButtonGroupBox)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setMargin(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.downloadPushButton = QtGui.QPushButton(self.widget_5)
        self.downloadPushButton.setObjectName(_fromUtf8("downloadPushButton"))
        self.horizontalLayout_7.addWidget(self.downloadPushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.widget = QtGui.QWidget(self.downloadButtonGroupBox)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.secondsBeforeSpinBox = QtGui.QSpinBox(self.widget)
        self.secondsBeforeSpinBox.setMaximum(3600)
        self.secondsBeforeSpinBox.setSingleStep(10)
        self.secondsBeforeSpinBox.setProperty("value", 60)
        self.secondsBeforeSpinBox.setObjectName(_fromUtf8("secondsBeforeSpinBox"))
        self.horizontalLayout_3.addWidget(self.secondsBeforeSpinBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.widget, QtCore.Qt.AlignLeft)
        self.widget_2 = QtGui.QWidget(self.downloadButtonGroupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setMargin(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.secondsAfterSpinBox = QtGui.QSpinBox(self.widget_2)
        self.secondsAfterSpinBox.setMaximum(21600)
        self.secondsAfterSpinBox.setSingleStep(100)
        self.secondsAfterSpinBox.setProperty("value", 600)
        self.secondsAfterSpinBox.setObjectName(_fromUtf8("secondsAfterSpinBox"))
        self.horizontalLayout_4.addWidget(self.secondsAfterSpinBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.widget_2, QtCore.Qt.AlignLeft)
        self.downloadStatusLabel = QtGui.QLabel(self.downloadButtonGroupBox)
        self.downloadStatusLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.downloadStatusLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.downloadStatusLabel.setText(_fromUtf8(""))
        self.downloadStatusLabel.setObjectName(_fromUtf8("downloadStatusLabel"))
        self.verticalLayout_6.addWidget(self.downloadStatusLabel, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.downloadButtonGroupBox)
        self.saveButtonGroupBox = QtGui.QGroupBox(self.topFrame)
        self.saveButtonGroupBox.setObjectName(_fromUtf8("saveButtonGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.saveButtonGroupBox)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_6 = QtGui.QWidget(self.saveButtonGroupBox)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setMargin(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.savePushButton = QtGui.QPushButton(self.widget_6)
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_8.addWidget(self.savePushButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widget_3 = QtGui.QWidget(self.saveButtonGroupBox)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.saveDirectoryPushButton = QtGui.QPushButton(self.widget_3)
        self.saveDirectoryPushButton.setObjectName(_fromUtf8("saveDirectoryPushButton"))
        self.horizontalLayout_5.addWidget(self.saveDirectoryPushButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.widget_3, QtCore.Qt.AlignLeft)
        self.widget_4 = QtGui.QWidget(self.saveButtonGroupBox)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setMargin(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.saveFormatComboBox = QtGui.QComboBox(self.widget_4)
        self.saveFormatComboBox.setObjectName(_fromUtf8("saveFormatComboBox"))
        self.horizontalLayout_6.addWidget(self.saveFormatComboBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_5.addWidget(self.widget_4, QtCore.Qt.AlignLeft)
        self.saveStatusLabel = QtGui.QLabel(self.saveButtonGroupBox)
        self.saveStatusLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.saveStatusLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.saveStatusLabel.setText(_fromUtf8(""))
        self.saveStatusLabel.setObjectName(_fromUtf8("saveStatusLabel"))
        self.verticalLayout_5.addWidget(self.saveStatusLabel, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.saveButtonGroupBox)
        self.verticalLayout.addWidget(self.topFrame)
        self.selectionTableFrame = QtGui.QFrame(WaveformDialog)
        self.selectionTableFrame.setMinimumSize(QtCore.QSize(1200, 900))
        self.selectionTableFrame.setObjectName(_fromUtf8("selectionTableFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.selectionTableFrame)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.filterGroupBox = QtGui.QGroupBox(self.selectionTableFrame)
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.filterGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.eventComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.eventComboBox.setObjectName(_fromUtf8("eventComboBox"))
        self.horizontalLayout_2.addWidget(self.eventComboBox)
        self.networkComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.networkComboBox.setObjectName(_fromUtf8("networkComboBox"))
        self.horizontalLayout_2.addWidget(self.networkComboBox)
        self.stationComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.stationComboBox.setObjectName(_fromUtf8("stationComboBox"))
        self.horizontalLayout_2.addWidget(self.stationComboBox)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.filterGroupBox)
        self.selectionLabel = QtGui.QLabel(self.selectionTableFrame)
        self.selectionLabel.setObjectName(_fromUtf8("selectionLabel"))
        self.verticalLayout_2.addWidget(self.selectionLabel)
        self.selectionTable = QtGui.QTableWidget(self.selectionTableFrame)
        self.selectionTable.setMinimumSize(QtCore.QSize(500, 100))
        self.selectionTable.setShowGrid(False)
        self.selectionTable.setGridStyle(QtCore.Qt.NoPen)
        self.selectionTable.setObjectName(_fromUtf8("selectionTable"))
        self.selectionTable.setColumnCount(0)
        self.selectionTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.selectionTable)
        self.verticalLayout.addWidget(self.selectionTableFrame)

        self.retranslateUi(WaveformDialog)
        QtCore.QMetaObject.connectSlotsByName(WaveformDialog)

    def retranslateUi(self, WaveformDialog):
        WaveformDialog.setWindowTitle(_translate("WaveformDialog", "Dialog", None))
        self.downloadButtonGroupBox.setTitle(_translate("WaveformDialog", "Download / Preview Waveforms", None))
        self.downloadPushButton.setText(_translate("WaveformDialog", "Start / Stop", None))
        self.label.setText(_translate("WaveformDialog", "Waveform start (secs before P-wave)", None))
        self.label_2.setText(_translate("WaveformDialog", "Waveform end (secs after P-wave)", None))
        self.saveButtonGroupBox.setTitle(_translate("WaveformDialog", "Save / Reformat Waveforms", None))
        self.savePushButton.setText(_translate("WaveformDialog", "Start / Stop", None))
        self.label_3.setText(_translate("WaveformDialog", "To:", None))
        self.saveDirectoryPushButton.setText(_translate("WaveformDialog", "Directory", None))
        self.label_4.setText(_translate("WaveformDialog", "As:", None))
        self.filterGroupBox.setTitle(_translate("WaveformDialog", "Table Filters", None))
        self.selectionLabel.setText(_translate("WaveformDialog", "All Event-SNCL Waveforms", None))

