# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaveformDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WaveformDialog(object):
    def setupUi(self, WaveformDialog):
        WaveformDialog.setObjectName(_fromUtf8("WaveformDialog"))
        WaveformDialog.resize(1224, 1103)
        self.verticalLayout = QtGui.QVBoxLayout(WaveformDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topFrame = QtGui.QFrame(WaveformDialog)
        self.topFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.topFrame.setObjectName(_fromUtf8("topFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.downloadGroupBox = QtGui.QGroupBox(self.topFrame)
        self.downloadGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.downloadGroupBox.setObjectName(_fromUtf8("downloadGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.downloadGroupBox)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget = QtGui.QWidget(self.downloadGroupBox)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.secondsBeforeLabel = QtGui.QLabel(self.widget)
        self.secondsBeforeLabel.setObjectName(_fromUtf8("secondsBeforeLabel"))
        self.horizontalLayout_3.addWidget(self.secondsBeforeLabel)
        self.secondsBeforeSpinBox = QtGui.QSpinBox(self.widget)
        self.secondsBeforeSpinBox.setMaximum(3600)
        self.secondsBeforeSpinBox.setSingleStep(10)
        self.secondsBeforeSpinBox.setProperty("value", 60)
        self.secondsBeforeSpinBox.setObjectName(_fromUtf8("secondsBeforeSpinBox"))
        self.horizontalLayout_3.addWidget(self.secondsBeforeSpinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.widget, QtCore.Qt.AlignLeft)
        self.widget_2 = QtGui.QWidget(self.downloadGroupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setMargin(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.secondsAfterLabel = QtGui.QLabel(self.widget_2)
        self.secondsAfterLabel.setObjectName(_fromUtf8("secondsAfterLabel"))
        self.horizontalLayout_4.addWidget(self.secondsAfterLabel)
        self.secondsAfterSpinBox = QtGui.QSpinBox(self.widget_2)
        self.secondsAfterSpinBox.setMaximum(21600)
        self.secondsAfterSpinBox.setSingleStep(100)
        self.secondsAfterSpinBox.setProperty("value", 600)
        self.secondsAfterSpinBox.setObjectName(_fromUtf8("secondsAfterSpinBox"))
        self.horizontalLayout_4.addWidget(self.secondsAfterSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.widget_2, QtCore.Qt.AlignLeft)
        self.widget_5 = QtGui.QWidget(self.downloadGroupBox)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setMargin(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.downloadToolButton = QtGui.QToolButton(self.widget_5)
        self.downloadToolButton.setMinimumSize(QtCore.QSize(200, 0))
        self.downloadToolButton.setText(_fromUtf8(""))
        self.downloadToolButton.setCheckable(True)
        self.downloadToolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.downloadToolButton.setObjectName(_fromUtf8("downloadToolButton"))
        self.horizontalLayout_7.addWidget(self.downloadToolButton)
        self.downloadStatusLabel = QtGui.QLabel(self.widget_5)
        self.downloadStatusLabel.setObjectName(_fromUtf8("downloadStatusLabel"))
        self.horizontalLayout_7.addWidget(self.downloadStatusLabel, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.downloadGroupBox)
        self.saveGroupBox = QtGui.QGroupBox(self.topFrame)
        self.saveGroupBox.setObjectName(_fromUtf8("saveGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.saveGroupBox)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_3 = QtGui.QWidget(self.saveGroupBox)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.saveDirectoryLabel = QtGui.QLabel(self.widget_3)
        self.saveDirectoryLabel.setObjectName(_fromUtf8("saveDirectoryLabel"))
        self.horizontalLayout_5.addWidget(self.saveDirectoryLabel)
        self.saveDirectoryPushButton = QtGui.QPushButton(self.widget_3)
        self.saveDirectoryPushButton.setObjectName(_fromUtf8("saveDirectoryPushButton"))
        self.horizontalLayout_5.addWidget(self.saveDirectoryPushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.widget_3, QtCore.Qt.AlignLeft)
        self.widget_4 = QtGui.QWidget(self.saveGroupBox)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setMargin(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.saveFormatLabel = QtGui.QLabel(self.widget_4)
        self.saveFormatLabel.setObjectName(_fromUtf8("saveFormatLabel"))
        self.horizontalLayout_6.addWidget(self.saveFormatLabel)
        self.saveFormatComboBox = QtGui.QComboBox(self.widget_4)
        self.saveFormatComboBox.setObjectName(_fromUtf8("saveFormatComboBox"))
        self.horizontalLayout_6.addWidget(self.saveFormatComboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.widget_4, QtCore.Qt.AlignLeft)
        self.widget_6 = QtGui.QWidget(self.saveGroupBox)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setMargin(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.saveToolButton = QtGui.QToolButton(self.widget_6)
        self.saveToolButton.setMinimumSize(QtCore.QSize(200, 0))
        self.saveToolButton.setText(_fromUtf8(""))
        self.saveToolButton.setCheckable(True)
        self.saveToolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.saveToolButton.setObjectName(_fromUtf8("saveToolButton"))
        self.horizontalLayout_8.addWidget(self.saveToolButton)
        self.saveStatusLabel = QtGui.QLabel(self.widget_6)
        self.saveStatusLabel.setObjectName(_fromUtf8("saveStatusLabel"))
        self.horizontalLayout_8.addWidget(self.saveStatusLabel, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.horizontalLayout.addWidget(self.saveGroupBox)
        self.verticalLayout.addWidget(self.topFrame)
        self.selectionTableFrame = QtGui.QFrame(WaveformDialog)
        self.selectionTableFrame.setMinimumSize(QtCore.QSize(1200, 900))
        self.selectionTableFrame.setObjectName(_fromUtf8("selectionTableFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.selectionTableFrame)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.filterGroupBox = QtGui.QGroupBox(self.selectionTableFrame)
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.filterGroupBox)
        self.horizontalLayout_2.setMargin(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.eventComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.eventComboBox.setObjectName(_fromUtf8("eventComboBox"))
        self.horizontalLayout_2.addWidget(self.eventComboBox)
        self.networkComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.networkComboBox.setObjectName(_fromUtf8("networkComboBox"))
        self.horizontalLayout_2.addWidget(self.networkComboBox)
        self.stationComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.stationComboBox.setObjectName(_fromUtf8("stationComboBox"))
        self.horizontalLayout_2.addWidget(self.stationComboBox)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.filterGroupBox)
        self.selectionTable = QtGui.QTableWidget(self.selectionTableFrame)
        self.selectionTable.setMinimumSize(QtCore.QSize(500, 100))
        self.selectionTable.setShowGrid(False)
        self.selectionTable.setGridStyle(QtCore.Qt.NoPen)
        self.selectionTable.setObjectName(_fromUtf8("selectionTable"))
        self.selectionTable.setColumnCount(0)
        self.selectionTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.selectionTable)
        self.verticalLayout.addWidget(self.selectionTableFrame)

        self.retranslateUi(WaveformDialog)
        QtCore.QMetaObject.connectSlotsByName(WaveformDialog)

    def retranslateUi(self, WaveformDialog):
        WaveformDialog.setWindowTitle(_translate("WaveformDialog", "Dialog", None))
        self.downloadGroupBox.setTitle(_translate("WaveformDialog", "Download / Preview Waveforms", None))
        self.secondsBeforeLabel.setText(_translate("WaveformDialog", "Waveform start (secs before P-wave)", None))
        self.secondsAfterLabel.setText(_translate("WaveformDialog", "Waveform end (secs after P-wave)", None))
        self.downloadStatusLabel.setText(_translate("WaveformDialog", "Download status", None))
        self.saveGroupBox.setTitle(_translate("WaveformDialog", "Save Waveforms", None))
        self.saveDirectoryLabel.setText(_translate("WaveformDialog", "To:", None))
        self.saveDirectoryPushButton.setText(_translate("WaveformDialog", "Directory", None))
        self.saveFormatLabel.setText(_translate("WaveformDialog", "As:", None))
        self.saveStatusLabel.setText(_translate("WaveformDialog", "Save status", None))
        self.filterGroupBox.setTitle(_translate("WaveformDialog", "Table Filters", None))

